#pragma once

/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  %FILE_NAME%
 *  subm:  %SUBMODEL_NAME%
 *  model: %MODEL_NAME%
 *  expmt: %EXPERIMENT_NAME%
 *  date:  %GENERATION_DATE%
 *  time:  %GENERATION_TIME%
 *  user:  %USER_NAME%
 *  from:  %COMPANY_NAME%
 *  build: %GENERATION_BUILD%
 *
 **********************************************************/

/* This file describes the model functions
 that are supplied for computation.

 The model itself is the %SUBMODEL_NAME%Model.cpp file
 */

#include "%SUBMODEL_NAME%Model.hpp"

/* OROCOS include files */
#include <rtt/TaskContext.hpp>
#include <rtt/Logger.hpp>
#include <rtt/Port.hpp>
#include <rtt/Activity.hpp>
#include <rtt/RTT.hpp>
#include <rtt/Property.hpp>
#include <rtt/PropertyBag.hpp>
#include <rtt/Time.hpp>
#include <rtt/types/CArrayTypeInfo.hpp>

#include "Adapter20Sim.h"

#define COMPUTATION_TIME_MEASUREMENT 1

#ifdef COMPUTATION_TIME_MEASUREMENT
#include <rtt/os/TimeService.hpp>
#include <rtt/Time.hpp>
#endif

namespace %MODEL_NAME%
{
	using namespace common20sim;

	class %SUBMODEL_NAME%: public %SUBMODEL_NAME%Model , public RTT::TaskContext
	{
	public:
		//enum stateflags_%SUBMODEL_NAME% {initialrun, mainrun, finished};

		/**
		 * %SUBMODEL_NAME% constructor
		 */
		%SUBMODEL_NAME%(std::string name = "%SUBMODEL_NAME%");

		/**
		 * %SUBMODEL_NAME% destructor
		 */
		virtual ~%SUBMODEL_NAME%(void);

		/**
		 * %SUBMODEL_NAME% configuration code and returns false if startup fails
		 */
		bool configureHook ();

		/**
		 * %SUBMODEL_NAME% startUp code and returns false if startup fails
		 */
		bool startHook ();

		/**
		 * %SUBMODEL_NAME% Calculation executed in this Hook.
		 */
		void updateHook ();

		/**
		 * %SUBMODEL_NAME% Terminate
		 */
		void stopHook ();

		double getTime(void);

		virtual bool setPeriod(RTT::Seconds s);

	protected:
    virtual void CopyInputsToVariables();

    virtual void CopyVariablesToOutputs();

    void setupComponentInterface();

		/**
		 * OROCOS Ports for input and ouput
		 */
		std::vector< Adapter20Sim<RTT::InputPort<flat_matrix_t > > > inputPorts;
		std::vector< Adapter20Sim<RTT::OutputPort<flat_matrix_t > > > outputPorts;
		std::vector< Adapter20Sim<RTT::Property<RTT::types::carray<double> > > > propertyPorts;

	private:
		RTT::PropertyBag* createPropertyBags(std::string name, RTT::PropertyBag* head);
		void cleanupPropertyBags(RTT::PropertyBag* p);

		std::string m_config_file;

#ifdef COMPUTATION_TIME_MEASUREMENT
	  RTT::Seconds m_cum_avg;
	  unsigned int m_cum_avg_counter;
#endif

	};

}
